"""empty message

Revision ID: 45cc3372d62d
Revises: 
Create Date: 2025-12-11 17:41:54.038913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45cc3372d62d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)
        batch_op.drop_index(batch_op.f('id'))
        batch_op.drop_constraint(batch_op.f('fk_tasks_topics'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'topics', ['topic_id'], ['id'])

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tasks_topics'), 'topics', ['topic_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('id'), ['id'], unique=True)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
