"""empty message

Revision ID: 4b4cc5dadfc7
Revises: 2ffedd98cf68
Create Date: 2026-01-15 21:56:02.566942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b4cc5dadfc7'
down_revision = '2ffedd98cf68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('solved_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('solved_tasks_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key('solved_tasks_user_fk', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solved_tasks', schema=None) as batch_op:
        batch_op.drop_constraint('solved_tasks_user_fk', type_='foreignkey')
        batch_op.create_foreign_key('solved_tasks_ibfk_2', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
