"""empty message

Revision ID: 4bc47b5326c7
Revises: b912eb6a8966
Create Date: 2026-01-15 19:26:52.446644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc47b5326c7'
down_revision = 'b912eb6a8966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic_translation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('topic_translation_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'topics', ['topic_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic_translation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('topic_translation_ibfk_1'), 'topics', ['topic_id'], ['id'])

    # ### end Alembic commands ###
