"""empty message

Revision ID: 70865ff6d5d4
Revises: 9f0cb8a49628
Create Date: 2026-01-04 00:35:12.049010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70865ff6d5d4'
down_revision = '9f0cb8a49628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('difficulty_label')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=1000), nullable=True))
        batch_op.add_column(sa.Column('difficulty_label', mysql.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
