"""empty message

Revision ID: 9f0cb8a49628
Revises: cf2e2817d2d7
Create Date: 2026-01-03 20:56:34.047281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0cb8a49628'
down_revision = 'cf2e2817d2d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic_translation', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['topic_id', 'lang'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic_translation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
