"""empty message

Revision ID: b912eb6a8966
Revises: 15c10490a25a
Create Date: 2026-01-14 20:33:30.728589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b912eb6a8966'
down_revision = '15c10490a25a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_translation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('task_translation_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tasks', ['task_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_translation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('task_translation_ibfk_1'), 'tasks', ['task_id'], ['id'])

    # ### end Alembic commands ###
