"""empty message

Revision ID: c0f27958a64b
Revises: 70865ff6d5d4
Create Date: 2026-01-04 00:37:24.844678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0f27958a64b'
down_revision = '70865ff6d5d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.Integer(), nullable=True))
        batch_op.drop_column('difficulty_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty_score', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
